### ISSUE TITLE
Can't access moderated object attributes

### ISSUE THREAD

**Issue by ursomniac** [dominno/django-moderation#134]
from your_app.models import MyModel

foo = MyModel.objects.get(pk=1)

foo.__dict__
{ ... all the things... }

foo.moderated_object.changed_object.__dict__
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'MyModel' object has no attribute 'moderated_object'

This doesn't match the behavior in the "How django-moderation works" part of the docs.

**Comment by ryuusenshi** [comment]
What's happening is that your models are not getting registered.

To check which models are registered you can do:
```python
from moderation import moderation

print moderation._registered_models
```
If you get an empty dict, it's because you haven't registered any models. Now if you have ``moderation.helpers.auto_discover()`` in your ``urls.py`` what you need to know is that the ``urls.py`` file is not loaded if you're using the shell (i.e. ``./manage.py shell``).

In order for your models to properly register, you should do this before you do anything else in you shell session:

```python
from moderation.helpers import auto_discover
auto_discover()
```
This might fix all the other problems you've been having, as well.

**Comment by ryuusenshi** [comment]
I got the ``example_project`` to work with ``django 1.7.8``.

Created a ``ExampleUserProfile`` and it didn't show up until it was approved.

**Comment by ryuusenshi** [comment]
@ursomniac Did this fix your problems? I'm unable to reproduce the problem.

**Comment by ursomniac** [comment]
No because most of my tests were done through the Admin which doesn't have the issue that using the shell has.   I'm happy to send you the code I have so that you can "reproduce the problem".

**Comment by ursomniac** [comment]
I'm back to square 1.

If I incorporate Django REST framework, it ignores django-moderation:  Event objects created through moderation - though 'pending' - appear in the Event table.   HOWEVER, using moderation in the shell returns the "correct" results (i,e., Event.objects.all() only returns approved objects) even though there are objects in the Event table that are unapproved.
